FROM python:3.6-alpine3.9

# Create user with home directory and no password and change workdir.
RUN adduser -Dh /api amivapi
WORKDIR /api

# Install packages.
RUN apk add --no-cache musl-dev gcc git bash && \
    #  libjpeg and zlib for Pillow
    apk add --no-cache zlib-dev jpeg-dev && \
    apk add --no-cache mongodb

# Install pip dependencies.
COPY requirements.txt /api/requirements.txt
RUN pip install -r /api/requirements.txt
RUN pip install pytest flake8

# We copy the code in last to make it fast to rebuild the container after
# changes.
COPY ./ /api

# Switch user
USER amivapi

ENTRYPOINT ["/api/test_with_db.sh"]
