#!/bin/sh

mkdir ./crontabs
echo "$CRON_TIME $(which amivapi) cron" > ./crontabs/$(whoami)

# -f foreground
# -d to log to stderr and be more verbose
# -c for crontab dir, readlink because an absolute path is needed
exec crond -f -d0 -c $(readlink -f ./crontabs)

