name: Pipeline on master

on:
  schedule:
    - cron: '5 4 * * 1'
  push:
    branches: [ master ]

jobs:
  tests:
    uses: ./.github/workflows/1_tests.yml

  build:
    uses: ./.github/workflows/1_build.yml
    needs: tests
    with:
      push: true

  deploy:
    uses: ./.github/workflows/1_deploy.yml
    needs: build
